import { defineConfig } from "tsup";

/**
 * Bundle the SDK into ESM chunks.
 *
 * Why: `tsc` + `moduleResolution: "Bundler"` emits relative imports verbatim
 * (e.g. `from "./accord"`), and Node's ESM loader REQUIRES explicit `.js`
 * extensions. The generated Codama output (regenerated by `make codegen`)
 * compounds this with ~110 extensionless specifiers. Shipping raw `tsc` output
 * therefore broke `@useaccord/sdk` under Node — the root cause of the CLI's
 * `MODULE_NOT_FOUND` on global install. Bundling resolves every specifier at
 * build time, so `dist/` is valid Node ESM regardless of source style.
 *
 * Layout: two entry chunks (`index`, `evidence/index`) matching the package
 * `exports` map, with shared code deduped via `splitting`. All runtime deps
 * stay external (resolved from consumers' node_modules); source + generated
 * Codama output get inlined. Type declarations are still emitted by `tsc
 * --emitDeclarationOnly` (see package.json `build`).
 */
export default defineConfig({
  entry: {
    index: "src/index.ts",
    "evidence/index": "src/evidence/index.ts",
  },
  format: ["esm"],
  target: "es2022",
  outDir: "dist",
  splitting: true,
  sourcemap: true,
  clean: true,
  keepNames: true,
  external: [
    "@solana/kit",
    "@noble/ciphers",
    "@noble/curves",
    "@noble/hashes",
    "bn.js",
  ],
});
