import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

/**
 * Static manifest generation for videos/.
 *
 * Remotion's webpack bundler needs static imports (no runtime directory
 * scanning), so every command (build/lint/test/studio/render) first
 * regenerates src/videos.gen.ts from the videos/ tree. The file is
 * gitignored: CI regenerates it from the tracked dirs alone.
 */

export interface VideoEntry {
  slug: string;
  /** Import path relative to src/videos.gen.ts. */
  importPath: string;
}

const SLUG_RE = /^[a-z][a-z0-9-]*$/;
/** Reserved dirs: the scaffold template is not a registrable video. */
const SKIP_DIRS: Record<string, true> = { _template: true };

const HEADER = `// GENERATED by \`pnpm --filter @useaccord/remotion sync\` — do not edit.
// Regenerated from apps/remotion/videos/ on every build/lint/test/studio/
// render run. Local video dirs are gitignored; CI only sees the tracked ones.`;

export function scanVideos(videosDir: string): VideoEntry[] {
  if (!existsSync(videosDir)) return [];
  const entries: VideoEntry[] = [];
  const errors: string[] = [];
  for (const ent of readdirSync(videosDir, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    if (SKIP_DIRS[ent.name]) continue;
    // Dirs starting with "_" are system/tracked dirs (e.g. _example);
    // author-created videos must be kebab-case.
    if (!ent.name.startsWith("_") && !SLUG_RE.test(ent.name)) {
      errors.push(`'${ent.name}' is not kebab-case (expected e.g. my-video)`);
      continue;
    }
    const hasIndex = ["index.ts", "index.tsx"].some((f) =>
      existsSync(path.join(videosDir, ent.name, f)),
    );
    if (!hasIndex) continue; // assets-only or work-in-progress dir
    entries.push({ slug: ent.name, importPath: `../videos/${ent.name}/index` });
  }
  if (errors.length > 0) {
    throw new Error(
      `apps/remotion videos — invalid directory names: ${errors.join("; ")}`,
    );
  }
  return entries.sort((a, b) => a.slug.localeCompare(b.slug));
}

function ident(slug: string): string {
  return `video_${slug.replace(/-/g, "_")}`;
}

export function renderManifest(entries: VideoEntry[]): string {
  const imports = entries
    .map((e) => `import { video as ${ident(e.slug)} } from "${e.importPath}";`)
    .join("\n");
  const items = entries.map((e) => `  ${ident(e.slug)},`).join("\n");
  return `${HEADER}
import type { VideoDefinition } from "./framework/video";
${imports}

export const videos: VideoDefinition[] = [
${items}
];
`;
}

export function sync(
  videosDir: string,
  outFile: string,
): { count: number; slugs: string[]; changed: boolean } {
  const entries = scanVideos(videosDir);
  const next = renderManifest(entries);
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
  if (prev !== next) {
    mkdirSync(path.dirname(outFile), { recursive: true });
    writeFileSync(outFile, next);
  }
  return {
    count: entries.length,
    slugs: entries.map((e) => e.slug),
    changed: prev !== next,
  };
}
