[package]
name = "accord"
version.workspace = true
edition.workspace = true
description = "VeriDAO Accord — general-purpose Schelling-point arbitration accord on Solana"

[lib]
crate-type = ["cdylib", "lib"]
name = "accord"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang.workspace = true
