// GENERATED by `pnpm --filter @useaccord/remotion sync` — do not edit.
// Regenerated from apps/remotion/videos/ on every build/lint/test/studio/
// render run. Local video dirs are gitignored; CI only sees the tracked ones.
import type { VideoDefinition } from "./framework/video";
import { video as video__example } from "../videos/_example/index";
import { video as video_v20260820_30s_accord_intro } from "../videos/v20260820-30s-accord-intro/index";
import { video as video_v20260820_30s_accord_intro_2 } from "../videos/v20260820-30s-accord-intro-2/index";
import { video as video_v20260820_30s_schelling_court_explainer } from "../videos/v20260820-30s-schelling-court-explainer/index";

export const videos: VideoDefinition[] = [
  video__example,
  video_v20260820_30s_accord_intro,
  video_v20260820_30s_accord_intro_2,
  video_v20260820_30s_schelling_court_explainer,
];
