name: main pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  landingpage:
    name: Update Landing Page
    if: always()
    secrets: inherit
    uses: ./.github/workflows/landing-page.yaml

  program-tests:
    name: Program Tests
    secrets: inherit
    uses: ./.github/workflows/program-tests.yml
    with:
      program: accord

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  build-evidence-docker:
    name: Build API Docker Image
    needs: [tests]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      registry: ghcr.io
      package: evidence-daemon
      version: "${{ github.ref_name }}.${{ github.run_number }}"
      push: ${{ github.event_name != 'pull_request' }}

  build-cranker-docker:
    name: Build API Docker Image
    needs: [tests]
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      registry: ghcr.io
      package: cranker
      version: "${{ github.ref_name }}.${{ github.run_number }}"
      push: ${{ github.event_name != 'pull_request' }}
