name: main pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  landingpage:
    name: Update Landing Page
    if: always()
    secrets: inherit
    uses: ./.github/workflows/landing-page.yaml

  program-tests:
    name: Program Tests
    secrets: inherit
    uses: ./.github/workflows/program-tests.yml
    with:
      program: accord
