name: Anchor Tests

on:
  push:
    branches: [main]
    paths:
      - "programs/**"
      - "tests/**"
      - "Anchor.toml"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  test:
    uses: solana-foundation/github-workflows/.github/workflows/test.yaml@v0.5.0
    with:
      program: "accord"
